### ISSUE TITLE
v1.1.3 on Homebridge v2.0.0 beta 20 Class constructor Service cannot be invoked without 'new'

### ISSUE THREAD

**Issue by fubu2k** [produdegr/homebridge-3em-energy-meter#25]
**Homebridhge v2.0.0 beta 20
Plugin v1.1.3**

Runs without error on Homebridge v1.8.4

**Crashes with**

[9/12/2024, 7:58:34 AM] Registering accessory 'homebridge-3em-energy-meter.3EMEnergyMeter'
[9/12/2024, 7:58:34 AM] [Energy Meter] Child bridge started successfully (plugin v1.1.3).
[9/12/2024, 7:58:34 AM] Loaded 0 cached accessories from cachedAccessories.0E9B79013445.
/homebridge/node_modules/homebridge-3em-energy-meter/index.js:104
                Service.call(this, displayName, '00000001-0000-1777-8000-775D67EC4377', subtype);
          ^
TypeError: Class constructor Service cannot be invoked without 'new'
    at new PowerMeterService (/homebridge/node_modules/homebridge-3em-energy-meter/index.js:104:11)
    at new EnergyMeter (/homebridge/node_modules/homebridge-3em-energy-meter/index.js:128:17)
    at ChildBridgeFork.startBridge (file:///homebridge/node_modules/homebridge/src/childBridgeFork.ts:176:52)
[9/12/2024, 7:58:34 AM] [Energy Meter] Child bridge ended (code 1, signal null). The child bridge ended unexpectedly, which is normally due to the plugin not catching its errors properly. Please report this to the plugin developer by clicking on the 'Report An Issue' option in the plugin menu dropdown from the Homebridge UI. If there are related logs shown above, please include them in your report.

**Comment by produdegr** [comment]
This error should not hit there as I'm not constructing a Service.Call but formulating a new Var.
If you go ahead and naively put a "new" in the suggested place, then you get:

/var/lib/homebridge/node_modules/homebridge-3em-energy-meter/index.js:104
        new Service.call(this, displayName, '00000001-0000-1777-8000-775D67EC4377', subtype);
        ^
TypeError: Service.call is not a constructor
    at new PowerMeterService (/var/lib/homebridge/node_modules/homebridge-3em-energy-meter/index.js:104:9)
    at new EnergyMeter (/var/lib/homebridge/node_modules/homebridge-3em-energy-meter/index.js:128:20)
    at ChildBridgeFork.startBridge (file:///var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:176:52)

"TypeError: Service.call is not a constructor" because it isnt't indeed. So the first Type Error should not be happening.

Unfortunately rewriting this plugin based on the new plugin prototypes will not work for this implementation (for me at least).
As I'm not a JavaScript pro (I deal more with C and Delphi Pascal), If there is a good hearted and knowledgable person outthere knowing how to patch this, please drop a comment.

**Comment by thechris1992** [comment]
Hey! I fixed it for HB v2.0.0-beta.30 and works with v1.11.0 too ;)

Also i added a selection for what Energy Data is show (i only need the W to show in the Eve App)

I can‘t create a branch here so please add / exchange these files by our own. 
(normaly found in a path like:
/var/lib/homebridge/node_modules/homebridge-3em-energy-meter )
@fubu2k @produdegr 

[CHANGELOG.md](https://github.com/user-attachments/files/22665735/CHANGELOG.md)
[index.js](https://github.com/user-attachments/files/22665495/index.js)
[config.schema.json](https://github.com/user-attachments/files/22665496/config.schema.json)
[package.json](https://github.com/user-attachments/files/22665728/package.json)

**Comment by thechris1992** [comment]
and if this plugin is EOS / EOL you can use my fork:
https://github.com/thechris1992/homebridge-3em-energy-meter

**Comment by cleanev** [comment]
Hello @produdegr & @thechris1992 - 
I installed from thechris1992 and configured with instructions provided in github webpage. 
I am able to connect to local IP and look at the reading. Furthermore, I have added Shelly App and am able to see readings in the app (thru cloud). I have also installed and added Shelly into Eve app.

The challenge is that I keep getting this in my logs (debug enabled) —- 404 Not found.
I added password to 3EM and tried with username:admin and password:xxxxxxxxxx
As I was getting 404 error, I rebuilt pi 4 and homebridge from scratch and added ONLY this plugin **with no password in 3EM** and still errors continue as shown below.


What am I doing wrong and can you please guide me to fix this, please? 
Thanks in advance for your assistance

[12/20/2025, 1:13:52 PM] [ShellyEnergyMeter] Restarting child bridge...
[12/20/2025, 1:13:52 PM] Got SIGTERM, shutting down child bridge process...
[12/20/2025, 1:13:57 PM] [ShellyEnergyMeter] Child bridge process ended
[12/20/2025, 1:13:57 PM] [ShellyEnergyMeter] Process Ended. Code: 143, Signal: null
[12/20/2025, 1:14:04 PM] [ShellyEnergyMeter] Restarting Process...
[12/20/2025, 1:14:05 PM] [ShellyEnergyMeter] Launched child bridge with PID 471400
[12/20/2025, 1:14:08 PM] Registering platform 'homebridge-shelly-energy-meter.ShellyEnergyMeter'
[12/20/2025, 1:14:08 PM] [ShellyEnergyMeter] Loaded homebridge-shelly-energy-meter v2.0.0 child bridge successfully
[12/20/2025, 1:14:08 PM] Loaded 1 cached accessories from cachedAccessories.0ECDB1F73A9A.
[12/20/2025, 1:14:08 PM] [ShellyEnergyMeter] Updating existing accessory: EM
[12/20/2025, 1:14:08 PM] [ShellyEnergyMeter] [EM] Initialized 3EM with 3 connected phase(s)
[12/20/2025, 1:14:08 PM] [ShellyEnergyMeter] [EM] Reusing existing PowerMeter service with subtype: 10.2.2.97
[12/20/2025, 1:14:08 PM] Homebridge v1.11.1 (HAP v0.14.0) (ShellyEnergyMeter) is running on port 58327.
[12/20/2025, 1:14:08 PM] [ShellyEnergyMeter] [EM] Update failed: HTTP 404: Not Found
[12/20/2025, 1:14:09 PM] [ShellyEnergyMeter] [EM] History service initialized successfully
[12/20/2025, 1:14:18 PM] [ShellyEnergyMeter] [EM] Update failed: HTTP 404: Not Found
[12/20/2025, 1:14:28 PM] [ShellyEnergyMeter] [EM] Update failed: HTTP 404: Not Found
[12/20/2025, 1:14:38 PM] [ShellyEnergyMeter] [EM] Update failed: HTTP 404: Not Found
[12/20/2025, 1:14:48 PM] [ShellyEnergyMeter] [EM] Update failed: HTTP 404: Not Found
[12/20/2025, 1:14:58 PM] [ShellyEnergyMeter] [EM] Update failed: HTTP 404: Not Found
[12/20/2025, 1:15:08 PM] [ShellyEnergyMeter] [EM] Update failed: HTTP 404: Not Found

**Comment by thechris1992** [comment]
hey @cleanev please give me the output of your `<em-ip>/status`

sorry for the late reply. i also got an 3em and without user/pass on the device & no login creds in the config it works fine. if i add creds only to the config it also works... maybe you got a new device like the 3em pro?

**Comment by cleanev** [comment]
> hey [@cleanev](https://github.com/cleanev) please give me the output of your `<em-ip>/status`
> 
> sorry for the late reply. i also got an 3em and without user/pass on the device & no login creds in the config it works fine. if i add creds only to the config it also works... maybe you got a new device like the 3em pro?

Hi @thechris1992 - thanks for getting back here.
I tried to connect to http://10.2.2.97/status using browser and got ‘Not Found’ page, whereas http://10.2.2.97/#/em/0/overview displays a page with pertinent details.
I seem to have ShellyPro3EM.

Thanks

**Comment by thechris1992** [comment]
@cleanev take a look maybe here: https://github.com/pa-nic/homebridge-shelly-3em

**Comment by cleanev** [comment]
Thank you @thechris1992 - I moved over to this plugin and over to yours as earlier versions from pa-nic never registered well. I installed the newest version as of today but somehow nothing shows up in eve app so am planning to rebuild RPi yet again and see if that fares any better. 
Appreciate your time and effort.
